project:
  type: website

website:
  description: "A blog built with Quarto"
  title: "Applied-Bioinfo-Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
sidebar: {}

format:
  html:
    theme:
      - lux
      - morph
    css: styles.css
execute:
  freeze: auto



